#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows specific messages for certain iterations.
# Use a while loop to iterate from 1 to 20
count=1
while [ $count -le 20 ]; do
    case $count in
        4)
            echo -e "$count\nbad and then bad luck from China"
            ;;
        9)
            echo -e "$count\n and then bad luck from Japan"
            ;;
        17)
            echo -e "$count\n and then bad luck from Italy"
            ;;
        *)
            echo $count
            
    esac
   ((count ++))
done
