#!/usr/bin/env bash
# This script displays hours and minutes for a 24-hour period

hour=0

while [ $hour -lt 6 ]; do
    echo "Hour: $hour"
    minute=0
    while [ $minute -lt 60 ]; do
        echo $minute
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done

